### PR TITLE
Prepare 0.5.0 release

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
## Which problem is this PR solving?
Prepares 0.5.0 release.

## Short description of the changes
- Adds changelog entry

### CODE REVIEW

**Review by JamieDanielson — COMMENTED** [review]
should we bump buildevents to the new version (0.7.2 about to be released) before releasing a new orb?

**Review by robbkidd — DISMISSED** [review]
Seconding the recommendation to hold-off on release until after we update the orb to use [the currently pending v0.7.2 version of buildevents](https://github.com/honeycombio/buildevents/pull/136).

**Comment by MikeGoldsmith** [comment]
Updated buildevents dep and changelog entry 👍🏻

**Comment by MikeGoldsmith** [comment]
Looks like there's going to be another buildevents release soon to release the following - may as well wait for it here.
- https://github.com/honeycombio/buildevents/pull/137

**Comment by JamieDanielson** [comment]
🎉  buildevents [v0.8.0](https://github.com/honeycombio/buildevents/releases/tag/v0.8.0) has been released. One more update needed for the orb to bump to that level, then we'll be ready for release

**Comment by MikeGoldsmith** [comment]
Updated changelog preemptively on #60 being merged.

**Review by vreynolds — APPROVED** [review]

**Comment by MikeGoldsmith** [comment]
Updated changelog with buildevents bump to v0.8.0 - ready for review again 👍🏻

**Review by vreynolds — APPROVED** [review]

**Pull request merged**
